### ISSUE TITLE
styles.css incorrectly listed in thirpartylibs.xml file

### ISSUE THREAD

**Issue by danmarsden** [mebis-lp/moodle-mod_mootimeter#84]
as mentioned in #77 - the styles.css entry shouldn't be in the thirdpartylibs.xml file.

**Comment by danmarsden** [comment]
if your aim is to just do this for github actions - I'm curious to know if a env var like this works?
```
env:
 CODECHECKER_IGNORE_NAMES: 'styles.css'
```

but all good - we won't block approval on this one.

**Comment by PhMemmel** [comment]
Hi @danmarsden, thank you for the hint. I tested (see branch `test_GHA_ignore` and associated GHA runs) and unfortunately your proposed solution does not work, because it's not a codechecker issue, but `grunt stylelint` which has no env variable like codechecker. So we will have to stick with the thirdpartylibs "hack" until MDL-81263 is being integrated.

**Comment by danmarsden** [comment]
thanks - good to know!
